### ISSUE TITLE
myessentials.DepLoader missing files

### ISSUE THREAD

**Issue by spannerman79** [MyEssentials/MyEssentials-Core#13]
Forge: 1614
MyEssentials-Core-1.7.10-111-dev.jar
MyPermissions-1.7.10-50-dev.jar
MyTown2-1.7.10-340-dev.jar

    myessentials.deploader.Downloader:download:69]: Downloading file http://central.maven.org/maven2/com/esotericsoftware/reflectasm/reflectasm/1.09//reflectasm-1.09.jar
    [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: http://central.maven.org/maven2/com/esotericsoftware/reflectasm/reflectasm/1.09//reflectasm-1.09.jar

And so on, making the server crash out.

As I test I did `wget http://central.maven.org/maven2/com/esotericsoftware/reflectasm/reflectasm/1.09//reflectasm-1.09.jar` and it failed, but if i remove the extra slash - `wget http://central.maven.org/maven2/com/esotericsoftware/reflectasm/reflectasm/1.09/reflectasm-1.09.jar` it works.

**Comment by NocturnalSergal** [comment]
made a commit to patch this issue. if you can use gradlew to compile i reccommend downloading my fix and compiling it until the pull request is seen by the developer
